-- Root folder (parent_id = NULL)
INSERT INTO folders (parent_id, customer_id, user_id, name, folder_size, asset_count, status, thumbnail_id)
VALUES (NULL, 7, 9, 'Events', 0, 0, 'active', NULL);

-- 100 sample event folders under "Events" (parent_id = 1)
INSERT INTO folders (parent_id, customer_id, user_id, name, folder_size, asset_count, status, thumbnail_id) VALUES
(1, 7, 9, 'Rafael Birthday Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Joseph Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Paty Trip to Dallas', 0, 0, 'active', NULL),
(1, 7, 9, 'Clara and Mark Wedding', 0, 0, 'active', NULL),
(1, 7, 9, 'Anna Graduation', 0, 0, 'active', NULL),
(1, 7, 9, 'Lucas First Communion', 0, 0, 'active', NULL),
(1, 7, 9, 'David Engagement Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Sophie Sweet Sixteen', 0, 0, 'active', NULL),
(1, 7, 9, 'Olivia Family Picnic', 0, 0, 'active', NULL),
(1, 7, 9, 'Ethan Trip to Cancun', 0, 0, 'active', NULL),
(1, 7, 9, 'Mia Baby Shower', 0, 0, 'active', NULL),
(1, 7, 9, 'Daniel Beach Wedding', 0, 0, 'active', NULL),
(1, 7, 9, 'Laura Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Andres Birthday at Park', 0, 0, 'active', NULL),
(1, 7, 9, 'Samantha Engagement', 0, 0, 'active', NULL),
(1, 7, 9, 'Julia Corporate Event', 0, 0, 'active', NULL),
(1, 7, 9, 'Victor Wedding Reception', 0, 0, 'active', NULL),
(1, 7, 9, 'Camila Friends Reunion', 0, 0, 'active', NULL),
(1, 7, 9, 'Tommy Family Photoshoot', 0, 0, 'active', NULL),
(1, 7, 9, 'Isabella Quinceañera', 0, 0, 'active', NULL),
(1, 7, 9, 'Hector Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Natalia Trip to Los Angeles', 0, 0, 'active', NULL),
(1, 7, 9, 'George Anniversary Dinner', 0, 0, 'active', NULL),
(1, 7, 9, 'Maria Baby Gender Reveal', 0, 0, 'active', NULL),
(1, 7, 9, 'James Surprise Proposal', 0, 0, 'active', NULL),
(1, 7, 9, 'Nina Baptism Celebration', 0, 0, 'active', NULL),
(1, 7, 9, 'Roberto Family Vacation', 0, 0, 'active', NULL),
(1, 7, 9, 'Luis and Carla Engagement', 0, 0, 'active', NULL),
(1, 7, 9, 'Emma Christening', 0, 0, 'active', NULL),
(1, 7, 9, 'Sebastian Beach Photoshoot', 0, 0, 'active', NULL),
(1, 7, 9, 'Valeria Wedding in Austin', 0, 0, 'active', NULL),
(1, 7, 9, 'Noah First Birthday', 0, 0, 'active', NULL),
(1, 7, 9, 'David Corporate Retreat', 0, 0, 'active', NULL),
(1, 7, 9, 'Luna Family Gathering', 0, 0, 'active', NULL),
(1, 7, 9, 'Leo Engagement Session', 0, 0, 'active', NULL),
(1, 7, 9, 'Eva Outdoor Wedding', 0, 0, 'active', NULL),
(1, 7, 9, 'Miguel Birthday Dinner', 0, 0, 'active', NULL),
(1, 7, 9, 'Sofia Trip to New York', 0, 0, 'active', NULL),
(1, 7, 9, 'Andrea Graduation Photos', 0, 0, 'active', NULL),
(1, 7, 9, 'Jorge Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Carmen Friends Gathering', 0, 0, 'active', NULL),
(1, 7, 9, 'Henry Corporate Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Alicia Destination Wedding', 0, 0, 'active', NULL),
(1, 7, 9, 'Daniela Baby Photoshoot', 0, 0, 'active', NULL),
(1, 7, 9, 'Pablo Engagement Photos', 0, 0, 'active', NULL),
(1, 7, 9, 'Lucia Trip to Mexico', 0, 0, 'active', NULL),
(1, 7, 9, 'Marcos Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Evelyn Family Portraits', 0, 0, 'active', NULL),
(1, 7, 9, 'Diego College Graduation', 0, 0, 'active', NULL),
(1, 7, 9, 'Elena Engagement Dinner', 0, 0, 'active', NULL),
(1, 7, 9, 'Carlos and Sofia Wedding', 0, 0, 'active', NULL),
(1, 7, 9, 'Fernanda Sweet Sixteen', 0, 0, 'active', NULL),
(1, 7, 9, 'Ricardo Family BBQ', 0, 0, 'active', NULL),
(1, 7, 9, 'Isabel New Year Celebration', 0, 0, 'active', NULL),
(1, 7, 9, 'Liam Company Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Ana Baby Shower', 0, 0, 'active', NULL),
(1, 7, 9, 'Paula Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Mateo Engagement Photos', 0, 0, 'active', NULL),
(1, 7, 9, 'Rosa Wedding in Monterrey', 0, 0, 'active', NULL),
(1, 7, 9, 'Ivan Graduation Ceremony', 0, 0, 'active', NULL),
(1, 7, 9, 'Patricia Christmas Dinner', 0, 0, 'active', NULL),
(1, 7, 9, 'Raul Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Daniel and Mia Wedding', 0, 0, 'active', NULL),
(1, 7, 9, 'Leo Trip to Paris', 0, 0, 'active', NULL),
(1, 7, 9, 'Gabriela Engagement Shoot', 0, 0, 'active', NULL),
(1, 7, 9, 'Oscar Birthday Lunch', 0, 0, 'active', NULL),
(1, 7, 9, 'Beatriz Family Vacation', 0, 0, 'active', NULL),
(1, 7, 9, 'Diana Bridal Shower', 0, 0, 'active', NULL),
(1, 7, 9, 'Pedro Wedding Anniversary', 0, 0, 'active', NULL),
(1, 7, 9, 'Angela College Reunion', 0, 0, 'active', NULL),
(1, 7, 9, 'Camilo Trip to Miami', 0, 0, 'active', NULL),
(1, 7, 9, 'Laura Engagement Ceremony', 0, 0, 'active', NULL),
(1, 7, 9, 'Andres Family Picnic', 0, 0, 'active', NULL),
(1, 7, 9, 'Melissa Birthday Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Sergio Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Natalie Sweet Sixteen', 0, 0, 'active', NULL),
(1, 7, 9, 'Emilio Engagement Dinner', 0, 0, 'active', NULL),
(1, 7, 9, 'Carla Corporate Photos', 0, 0, 'active', NULL),
(1, 7, 9, 'Javier Family Getaway', 0, 0, 'active', NULL),
(1, 7, 9, 'Monica Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Andres Trip to Rome', 0, 0, 'active', NULL),
(1, 7, 9, 'Camila Family Photos', 0, 0, 'active', NULL),
(1, 7, 9, 'Victor Corporate Gala', 0, 0, 'active', NULL),
(1, 7, 9, 'Nicole Baby Shower', 0, 0, 'active', NULL),
(1, 7, 9, 'Adrian Engagement Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Andrea Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Pablo Birthday Celebration', 0, 0, 'active', NULL),
(1, 7, 9, 'Julieta Trip to Vegas', 0, 0, 'active', NULL),
(1, 7, 9, 'Luis Wedding in Guadalajara', 0, 0, 'active', NULL),
(1, 7, 9, 'Roberta Company Dinner', 0, 0, 'active', NULL),
(1, 7, 9, 'Hugo Family Brunch', 0, 0, 'active', NULL),
(1, 7, 9, 'Luciana Christening', 0, 0, 'active', NULL),
(1, 7, 9, 'Mario Retirement Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Sofia Wedding in Cabo', 0, 0, 'active', NULL),
(1, 7, 9, 'Rene Graduation Day', 0, 0, 'active', NULL),
(1, 7, 9, 'Paolo Engagement Photoshoot', 0, 0, 'active', NULL),
(1, 7, 9, 'Elisa Baptism', 0, 0, 'active', NULL),
(1, 7, 9, 'Miguel Trip to Chicago', 0, 0, 'active', NULL),
(1, 7, 9, 'Valentina Birthday Bash', 0, 0, 'active', NULL),
(1, 7, 9, 'Carlos Engagement Ceremony', 0, 0, 'active', NULL),
(1, 7, 9, 'Alejandra Family Vacation', 0, 0, 'active', NULL),
(1, 7, 9, 'Fernando Corporate Lunch', 0, 0, 'active', NULL),
(1, 7, 9, 'Lucia Friends Reunion', 0, 0, 'active', NULL),
(1, 7, 9, 'Matias Wedding in Dallas', 0, 0, 'active', NULL),
(1, 7, 9, 'Patricia Graduation Party', 0, 0, 'active', NULL),
(1, 7, 9, 'Elias Trip to Tulum', 0, 0, 'active', NULL),
(1, 7, 9, 'Gabriel Company Retreat', 0, 0, 'active', NULL),
(1, 7, 9, 'Rosa Anniversary Celebration', 0, 0, 'active', NULL),
(1, 7, 9, 'Julian Birthday Photoshoot', 0, 0, 'active', NULL),
(1, 7, 9, 'Lorena Engagement Dinner', 0, 0, 'active', NULL);

-- Subfolders for each of the 100 events
INSERT INTO folders (parent_id, customer_id, user_id, name, folder_size, asset_count, status, thumbnail_id)
SELECT id, 7, 9, 'Raw', 0, 0, 'active', NULL FROM folders WHERE parent_id = 1;

INSERT INTO folders (parent_id, customer_id, user_id, name, folder_size, asset_count, status, thumbnail_id)
SELECT id, 7, 9, 'Distribution', 0, 0, 'active', NULL FROM folders WHERE parent_id = 1;

